spring:
  datasource:
#   &serverTimezone=Asia/Shanghai   解决存储到数据库中的时间与当前时间相差8个小时的bug
#   &characterEncoding=utf8   解决存储到数据库中的中文乱码的bug
    url: jdbc:mysql://localhost:3306/test_database?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: test_database
    password: 880e6580b8
  jpa:
    show-sql: true